### PR TITLE
ECDH-1PU+A256KW support

### PR DESCRIPTION
**Pull request by cykoder**
Hello!

I found myself in need of supporting this key wrapping algorithm and thought I'd attempt to contribute it back to the repo, if that is wanted. Happy to address the code for any issues or differing way of doing things.

In short this PR allows for the `ECDH-1PU+A256KW` key wrapping algorithm to support JWE sender authentication.

### CODE REVIEW

**Comment by dlongley** [comment]
I should first say, thank you for the PR!

Hmm, so we'll have to figure out what we want to do here.

The point of `minimal-cipher` is to keep the API minimal to help avoid footguns. This means that when you're encrypting, there's only one way to do things in each new major version. This is one thing that distinguishes this library from others that are kitchen sinks of all possible encryption mechanisms (that rarely come with explicit "developer beware" warnings).

We can support additional methods of decryption from old versions to enable upgrading, but the point of this lib was to avoid adding optionality by just making "the best / most reasonable cipher decision" for the developer with each major release. The only optionality that has been supported to date has been choosing between NIST/FIPS-approved crypto and whatever today's "most recommended" crypto is (they can be the same, but needn't always be).

If we think that `ECDH-1PU+A256KW` is the way to go, then the right way to do this is to make a new major release that forces that to be the new recommended encryption mechanism; we shouldn't add an option for the developer to choose from.

I wonder if we need another layer of abstraction with appropriate tree-shaking to pull in the latest "recommended" crypto from another core lib, but I'd be worried about making things more complicated and harder to maintain by doing that.

**Comment by cykoder** [comment]
Hey, thanks for the response.

I could tell the library was intended to, of course, be minimal. However my thinking here is that itd be useful to provide a minimal option of supporting sender authenticated key wrapping aswell as sender unauthenticated. With this implementation the developer doesnt need to explicitly choose which to use, but rather its derived from the intended/received recipient algorithm - I hoped that may help alleviate some concerns of potential user confusion and footguns.

`ECDH-1PU+A256KW` with ChaCha enc is very closely related to the existing `ECDH-ES+A256KW` implementation (the only "real" difference being how Z/the secret is calculated) unlike the difference between FIPS and XChaCha20-Poly1305. Infact this can work with FIPS too afaik.

Although that being said, I'd argue that sender authenticated should be the "recommended" approch for JWEs but that my just be my primary use case of DIDComm biasing my view as both key wrapping algorithms have their use cases.

It's no trouble if it feels like its potentially bloating the library too much as I can just maintain the fork :)

**Comment by dlongley** [comment]
I think the way this can work is differentiating between sender-authenticated and sender-anonymous encryption. I think both use cases are valid and it should be possible to do either -- and there will be just one way of doing either:

1. sender-anonymous: ECDH-ES+A256KW
2. sender-authenticated: ECDH-1PU+A256KW

Getting to this PR and potentially making adjustments to make clear that either authenticated / anonymous mode is being used (perhaps with more API surface) will take time because we've got other higher priority items at the moment. However, I think there's a path forward here that makes sense and fits in with the spirit and purpose of this library.

**Comment by dlongley** [comment]
Merging this into a branch in this repo so we can make further changes to it to incorporate it into a future release.

**Pull request merged**
